app/notifications/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import UpdatesView

app_name = 'notifications'
urlpatterns = [
    url(r'^$', UpdatesView.as_view(), name='updates'),
]

app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib.auth import views as auth_views
#import registration.backends.default.views
from django.contrib.auth import views as auth_views

from utils import installed
#from sso.forms import RegistrationFormUniqueEmailBlocked
#from sso.custom_authorization_view import SpecialAuthorizationView

#from oauth2_provider import views as oauth_views

admin.autodiscover()
from django.conf import settings
from django.conf.urls import include, url
import logging


urlpatterns = [
    #url(r'^register/$', registration.backends.default.views.RegistrationView.as_view(form_class=RegistrationFormUniqueEmailBlocked)),

    url('', include('sso.urls')),
    url('', include('django.contrib.auth.urls')),
    url(r'^eve/', include('eve_api.urls')),
    url(r'^market/', include('market.urls')),
    url(r'^updates/', include('notifications.urls')),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #url(r'^o2/authorize/$', SpecialAuthorizationView.as_view(), name="authorize"),

    #url(r'^o2/token/$', oauth_views.TokenView.as_view(), name="token"),
    #url(r'^o2/revoke_token/$', oauth_views.RevokeTokenView.as_view(), name="revoke-token"),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if installed('sentry'):
    urlpatterns += [
        url(r'^sentry/', include('sentry.web.urls')),
    ]

if installed('nexus'):
    import nexus
    nexus.autodiscover()

    urlpatterns += [
        url(r'^admin/', include('nexus.site.urls')),
    ]
else:
    urlpatterns += [
        url(r'^admin/', admin.site.urls),
    ]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()


def handler500(request):
    """
    500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')
    return HttpResponseServerError(t.render({'request': request}))
    

app/notifications/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import uuid


class UpdateMessage(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    post_time = models.DateTimeField(default=timezone.now)
    subject = models.TextField()
    message = models.TextField()
    trigger_unread_widget = models.BooleanField(default=False)


class UpdateMessageReadReceipt(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_read = models.DateTimeField(default=timezone.now)
    message = models.ForeignKey(UpdateMessage, on_delete=models.CASCADE)

    @staticmethod
    def mark_messages_read(user, messages):
        """
        Returns list of unread messages that are now read
        :param user:
        :param messages:
        :return:
        """
        receipts_to_commit = []
        for message in messages:
            if not UpdateMessageReadReceipt.objects.filter(message=message,user=user).exists():
                receipts_to_commit.append(
                    UpdateMessageReadReceipt(
                        user=user,
                        message=message
                    )
                )

        UpdateMessageReadReceipt.objects.bulk_create(receipts_to_commit)
        return receipts_to_commit

app/notifications/views.py
from django.views.generic import TemplateView

import logging

from .models import UpdateMessage, UpdateMessageReadReceipt

logger = logging.getLogger(__name__)


class UpdatesView(TemplateView):
    template_name = 'notifications/updates_page.html'

    def get_context_data(self, **kwargs):
        ctx = super(UpdatesView, self).get_context_data(**kwargs)

        updates = UpdateMessage.objects.all().order_by('-post_time')

        ctx["updates"] = updates

        # if authenticated user, highlight unread
        if self.request.user.is_authenticated:
            messages_user_has_read = list(UpdateMessageReadReceipt.objects.filter(user=self.request.user).values_list('message_id', flat=True))
            UpdateMessageReadReceipt.mark_messages_read(self.request.user, updates)

        else:
            messages_user_has_read = updates.values_list('id', flat=True)
        ctx["updates_read"] = messages_user_has_read

        return ctx

app/notifications/templates/notifications/notification_button.html
{% load get_news_notification_count %}

{% if request.user.is_authenticated %}
    <a href="{% url 'notifications:updates' %}" id="view-krabacus-news-has-notifications-authed">
        <span class="badge badge-primary">
        {% with notification_count=request.user|get_news_notification_count %}
        {% if notification_count %}
            Updates <span class="badge badge-danger">{{notification_count}}</span>
        {% else %}
            Updates
        {% endif %}
        {% endwith %}
        </span>
    </a>
{% else %}
    <a href="{% url 'notifications:updates' %}" id="view-krabacus-news-has-notifications-not-authed">
        <span class="badge badge-primary">
        Updates
        </span>
    </a>
{% endif %}

app/notifications/templates/notifications/updates_page.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}
{% load waffle_tags %}

{% block title %}News & Updates{% endblock %}

{% block css %}
{% endblock %}



{% block content %}
  <div class="container">
<div class="card">

  <div class="card-body">
        <h3>News & Updates</h3>

      {% for update in updates %}
            <div class="container">
            <div class="card bg-secondary {% if update.pk in updates_read %}border-secondary{% else %}border-success{% endif %}">
              <div class="card-body">
                  <h5 class="card-title">{% if update.pk in updates_read %}{% else %}<span class="badge badge-success">New!</span>{% endif %} {{update.subject}} </h5>
                <h6 class="card-subtitle mb-2 text-muted">Posted {{update.post_time}}</h6>
                <p class="card-text">
                    {% autoescape off %}{{update.message}}{% endautoescape %}
                </p>
              </div>
            </div>
            </div>
        <br>

      {% endfor %}
  </div>
    </div>
</div>
{% endblock %}




{% block footer %}
{% endblock %}