app/market/urls.py
from django.conf.urls import url

from .models import *
from .tasks import *
from .views import *
from .autocomplete import ItemGroupAutocomplete


app_name = 'market'
urlpatterns = [
    url(r'^item_group_autocomplete/$', ItemGroupAutocomplete.as_view(), name='item-group-autocomplete'),
    url(r'^routes/create/$', CreateRouteView.as_view(), name='create-route'),
    url(r'^routes/eye/data/(?P<pk>[0-9a-f-]+)/$', EyeofKrabData.as_view(), name='eye-data'),
    #url(r'^routes/eye/(?P<pk>\d+)/$', EyeOfKrabView.as_view(), name='eye-view'),
    url(r'^routes/view/(?P<pk>[0-9a-f-]+)/$', SingleRouteView.as_view(), name='route-view'),
    url(r'^routes/edit/$', EditRouteView.as_view(), name='route-edit'),
    url(r'^routes/delete/(?P<pk>[0-9a-f-]+)/$', DeleteRouteView.as_view(), name='route-delete'),
    #url(r'^routes/transactions/(?P<pk>\d+)/$', TransactionsView.as_view(), name='transaction-view'),
    url(r'^routes/transactions/data/(?P<pk>[0-9a-f-]+)/$', TransactionsData.as_view(), name='transaction-data'),
    url(r'^routes/orders/data/(?P<pk>[0-9a-f-]+)/$', OrdersData.as_view(), name='order-data'),
    url(r'^routes/orders/profit/(?P<pk>[0-9a-f-]+)/$', ProfitData.as_view(), name='profit-data'),
    url(r'^routes/shopping/edit/(?P<pk>[0-9a-f-]+)/$', shopping_list_edit_view, name='edit-shopping-list'),
    url(r'^routes/shopping/clear/(?P<pk>[0-9a-f-]+)/$', shopping_list_clear_view, name='clear-shopping-list'),
    url(r'^routes/shopping/data/(?P<pk>[0-9a-f-]+)/$', ShoppingListData.as_view(), name='shopping-list-data'),

    url(r'^routes/view/demo/$', SingleRouteDemoView.as_view(), name='route-demo-view'),

    url(r'^routes/$', RoutesView.as_view(), name='routes'),
]

app/sso/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from sso import views, auth_views
from sso.autocomplete import UserAutcomplete
from market.views import CreateRouteView

app_name = 'sso'
urlpatterns = [
    url(r'^$', views.ProfileView.as_view(), name='home'),

    # overwrites django default
    url(r'^login/$', auth_views.EsiLoginAsAuthenticationView.as_view(), name="esi-login"),
    url(r'^add_key/$', auth_views.EsiLoginToAddKeyView.as_view(), name="esi-add-key"),


    url(r'^o2/callback/$', auth_views.EsiLoginCallbackView.as_view(), name="esi-login-callback"),
    url(r'^user_autocomplete/$', UserAutcomplete.as_view(), name="user-autocomplete"),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profilefst/$', CreateRouteView.as_view(), name='profilefirst'),
    url(r'^analytics/$', views.AnalyticsView.as_view(), name='analytics'),
    url(r'^account/$', views.AccountView.as_view(), name='account'),
    url(r'^subscribe/$', views.AccountView.as_view(), name='subscribe'),
    url(r'^key_add_success/$', auth_views.KeyAddSuccessView.as_view(), name='key-add-success'),
    #url(r'roles', views.sso_role_view, name="sso-get-roles"),

]

app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib.auth import views as auth_views
#import registration.backends.default.views
from django.contrib.auth import views as auth_views

from utils import installed
#from sso.forms import RegistrationFormUniqueEmailBlocked
#from sso.custom_authorization_view import SpecialAuthorizationView

#from oauth2_provider import views as oauth_views

admin.autodiscover()
from django.conf import settings
from django.conf.urls import include, url
import logging


urlpatterns = [
    #url(r'^register/$', registration.backends.default.views.RegistrationView.as_view(form_class=RegistrationFormUniqueEmailBlocked)),

    url('', include('sso.urls')),
    url('', include('django.contrib.auth.urls')),
    url(r'^eve/', include('eve_api.urls')),
    url(r'^market/', include('market.urls')),
    url(r'^updates/', include('notifications.urls')),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #url(r'^o2/authorize/$', SpecialAuthorizationView.as_view(), name="authorize"),

    #url(r'^o2/token/$', oauth_views.TokenView.as_view(), name="token"),
    #url(r'^o2/revoke_token/$', oauth_views.RevokeTokenView.as_view(), name="revoke-token"),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if installed('sentry'):
    urlpatterns += [
        url(r'^sentry/', include('sentry.web.urls')),
    ]

if installed('nexus'):
    import nexus
    nexus.autodiscover()

    urlpatterns += [
        url(r'^admin/', include('nexus.site.urls')),
    ]
else:
    urlpatterns += [
        url(r'^admin/', admin.site.urls),
    ]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()


def handler500(request):
    """
    500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')
    return HttpResponseServerError(t.render({'request': request}))
    

app/sso/models.py
from datetime import datetime, timedelta
import types
import hashlib

from django.db import models
from django.db.models import signals
from django.contrib.auth.models import User, Group
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.conf import settings
from django.utils import timezone


from eve_api.models import EVEPlayerCharacter
from eve_api.models import EVEPlayerCharacter

from notifications.models import UpdateMessage, UpdateMessageReadReceipt

import waffle

from operator import itemgetter

## Exceptions





class SSOUser(models.Model):
    """ Extended SSO User Profile options """

    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE)
    primary_character = models.ForeignKey(EVEPlayerCharacter,null=True, default=None, on_delete=models.CASCADE)
    def __unicode__(self):
        return self.user.__unicode__()

    @property
    def get_primary_character(self):
        return "lol"

    @staticmethod
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            profile, created = SSOUser.objects.get_or_create(user=instance)

            # create notification receipts
            all_messages = UpdateMessage.objects.all()
            read_receipts = []
            for message in all_messages:
                read_receipts.append(
                    UpdateMessageReadReceipt(
                        user = instance,
                        message = message,
                    )
                )
            UpdateMessageReadReceipt.objects.bulk_create(read_receipts)



signals.post_save.connect(SSOUser.create_user_profile, sender=User)

app/sso/views.py
import hashlib
import logging
import random
import re
import unicodedata
from operator import attrgetter, itemgetter

import oauthlib.oauth2.rfc6749.errors as oauth_errors
import waffle
from django.conf import settings
from requests_oauthlib import OAuth2Session
import requests
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.db.models import FloatField, Q, Sum
from django.http import (HttpResponseForbidden, HttpResponseNotFound,
                         HttpResponseRedirect, JsonResponse)
from django.shortcuts import get_object_or_404, redirect
from django.template import RequestContext
from braces.views import LoginRequiredMixin, PermissionRequiredMixin

from eve_api.tasks import update_eve_character_esi

from django.views.decorators.csrf import csrf_exempt
from django.views.generic import (DetailView, FormView, ListView, TemplateView,
                                  View)
from market.models import TradingRoute
from eve_api.models import CharacterAssociation, EsiKey

from django.core.exceptions import PermissionDenied
from .models import SSOUser
logger=logging.getLogger(__name__)


class ProfileView(TemplateView):
    template_name = 'sso/profile.html'

    def get(self, request, *args, **kwargs):

        return super(ProfileView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(ProfileView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            routes = TradingRoute.objects.filter(creator=self.request.user)
            ctx["routes"] = routes

        return ctx


class AnalyticsView(TemplateView):
    template_name = 'sso/analytics.html'

    def get(self, request, *args, **kwargs):

        return super(AnalyticsView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(AnalyticsView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated and self.request.user.is_superuser:
            users = User.objects.all()
            users_with_no_routes = []
            users_with_routes = []

            for u in users:
                if not TradingRoute.objects.filter(creator=u).exists():
                    # get number of esi chars
                    chars = EsiKey.objects.filter(owner=u, use_key=True)
                    users_with_no_routes.append({
                        "user": u,
                        "num_keys": len(chars)
                    })
                else:
                    routes = TradingRoute.objects.filter(creator=u)
                    most_recent = routes.filter(last_viewed__isnull=False).order_by('-last_viewed')
                    if not most_recent:
                        most_recent = None
                        last_viewed = None
                    else:
                        most_recent = most_recent[0]
                        last_viewed = most_recent.last_viewed

                    users_with_routes.append({
                        "user":u,
                        "num_routes": len(routes),
                        "most_recent_viewed": most_recent,
                        "most_recent_view_time": last_viewed
                    })
            ctx["users_with_routes"] = users_with_routes
            ctx["users_with_no_routes"] = users_with_no_routes
        else:
            raise PermissionDenied()

        return ctx

class AccountView(TemplateView):
    template_name = 'sso/account.html'

    def get(self, request, *args, **kwargs):

        return super(AccountView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(AccountView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            characters = CharacterAssociation.objects.filter(owner = self.request.user, association_active=True)
            characters_with_keys = []
            characters_without_keys = []
            for association in characters:
                has_key = EsiKey.does_character_have_key(association.character.pk)
                if has_key:
                    characters_with_keys.append(association.character)
                else:
                    characters_without_keys.append(association.character)
            ctx["characters_with_keys"] = characters_with_keys
            ctx["characters_without_keys"] = characters_without_keys
            ctx["subscription"] = self.request.user.subscription
        else:
            raise PermissionDenied()

        return ctx

app/sso/templates/sso/account.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}
{% load waffle_tags %}
{% load fmt_isk %}

{% block title %}Manage Account{% endblock %}

{% block css %}
{% endblock %}


{% block content %}
<br>
<div class="card">
  <div class="card-body">
<h4>How to add subscription time</h4>
      Send ISK to <b>"Zanielyene"</b> ingame with the following payment code in the 'reason' field: <h4><b>{{request.user.subscription.pk}}</b></h4>
      Any ISK sent with the above payment code will be credited to your account, no matter what character you send it from.<br><br>

      <b>Common payment amounts</b>
      <div class="row">
        <div class="col-sm">
            300M ISK  - 60 days subscription time
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
            150M ISK  - 30 days subscription time
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
            75M ISK  - 15 days subscription time
        </div>
      </div>
  </div>
</div>

<br>
<div class="card">
  <div class="card-body">
<h4>Payments</h4>
      <table class="table table-striped table-bordered">
          <tr>
              <th>Date of payment</th>
              <th>Date payment credited</th>
              <th>Payment amount</th>
              <th>Source Character</th>
          </tr>
          {% for payment in subscription.payments %}
          <tr>
            <td>{{payment.payment_time_actual}}</td>
            <td>{{payment.payment_read_time}}</td>
            <td>{{payment.amount | intcomma}}</td>
            <td>{% if not payment.source_character %}Krabacus{% else %}{{payment.source_character.name}}{% endif %}</td>
          </tr>
          {% endfor %}
      </table>
      Payments update every hour or so.
  </div>
</div>
<br>
<div class="card">
  <div class="card-body">

<h4>Characters</h4>
  <div class="row">
    <div class="col-sm">
        <b>Characters with active ESI keys</b>
    </div>
  </div>
    {% for char in characters_with_keys %}
      <div class="row">
        <div class="col-sm">
            <img src="https://image.eveonline.com/Character/{{char.pk}}_32.jpg">
            {{char}}
        </div>
      </div>
    {% endfor %}

  <div class="row">
    <div class="col-sm">
        <b>Characters without ESI keys</b>
    </div>
  </div>

    {% for char in characters_without_keys %}
      <div class="row">
        <div class="col-sm">
            <img src="https://image.eveonline.com/Character/{{char.pk}}_32.jpg">
            {{char}}
        </div>
      </div>
    {% endfor %}

  </div>
</div>
<br>
{% endblock %}


{% block footer %}
{% endblock %}

app/sso/templates/sso/analytics.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}
{% load waffle_tags %}
{% load fmt_isk %}

{% block title %}Manage Account{% endblock %}

{% block css %}
{% endblock %}


{% block content %}
<br>
<div class="card">
  <div class="card-body">
        <h5>Users with no routes</h5>
        <table class="table table-bordered">
            <tr>
                <td>
                    User id
                </td>
                <td>
                    username
                </td>
                <td>
                    first logged in
                </td>
                <td>
                    last logged in
                </td>

                <td>
                    # of chars with full esi keys
                </td>
            </tr>
            {% for u in users_with_no_routes %}
            <tr>
                <td>{{u.user.pk}}</td>
                <td>{{u.user.username}}</td>
                <td>{{u.user.date_joined}}</td>
                <td>{{u.user.last_login}}</td>
                <td>{{u.num_keys}}</td>
            </tr>
            {% endfor %}
        </table>

      <h5>Users with routes</h5>
        <table class="table table-bordered">
            <tr>
                <td>
                    User id
                </td>
                <td>
                    username
                </td>
                <td>
                    first logged in
                </td>
                <td>
                    last logged in
                </td>

                <td>
                    # of routes
                </td>
                <td>
                    Most recent route viewed
                </td>
                <td>Most recent view time</td>
            </tr>
            {% for u in users_with_routes %}
            <tr>
                <td>{{u.user.pk}}</td>
                <td>{{u.user.username}}</td>
                <td>{{u.user.date_joined}}</td>
                <td>{{u.user.last_login}}</td>
                <td>{{u.num_routes}}</td>
                <td>{% if u.most_recent_viewed %}<a href="{% url 'market:route-view' u.most_recent_viewed.pk %}">{{u.most_recent_viewed}}</a> {% else %}{{u.most_recent_viewed}}{% endif %}</td>
                <td>{{u.most_recent_view_time}}</td>
            </tr>
            {% endfor %}
        </table>
  </div>
</div>


<br>
{% endblock %}


{% block footer %}
{% endblock %}

app/sso/templates/sso/key_add_success.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}
{% load waffle_tags %}

{% block title %}Home{% endblock %}

{% block css %}
    <style type="text/css">
        .profilebox {
            padding: 0px;
        }
        .profilebox h3 {
            margin-top: 5px;
        }
        .profilebox hr {
            margin-top: 5px;
            margin-bottom: 10px;
            border-top: 1px solid darkgray;
        }
        .keytable th {
            text-align: right;
        }
        .keytable td {
            padding-left: 10px;
        }

    </style>
{% endblock %}



{% block content %}
{% if user.is_authenticated %}

<div class="card">
  <div class="card-body">
      <h2>Key added successfully, window closing in 3 seconds.</h2>
  </div>
</div>

<script type="text/javascript">
 function closeWindow() {
    setTimeout(function() {
    window.close();
    }, 3000);
    }

    window.onload = closeWindow();
    </script>
{% endif %}
{% endblock %}

{% block footer %}
{% endblock %}

app/sso/templates/sso/profile.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}
{% load waffle_tags %}

{% block title %}Home{% endblock %}

{% block css %}
    <style type="text/css">
        .profilebox {
            padding: 0px;
        }
        .profilebox h3 {
            margin-top: 5px;
        }
        .profilebox hr {
            margin-top: 5px;
            margin-bottom: 10px;
            border-top: 1px solid darkgray;
        }
        .keytable th {
            text-align: right;
        }
        .keytable td {
            padding-left: 10px;
        }

    </style>
{% endblock %}



{% block content %}
{% if user.is_authenticated %}

<div class="card">
  <div class="card-body">
        <h3>Trading Routes</h3>
        {% for route in routes %}
        <a href="{% url 'market:route-view' route.pk %}">{{route}} ({{route.source_character}} -> {{route.destination_character}})</a>
        <br>
        {% endfor %}

        <a id="create-trade-route-repeat" href="{% url 'market:create-route' %}">Create new trading route</a>
  </div>
</div>


{% else %}

<br>
<div class="card" style="background-color:rgba(48, 48, 48, 0.95);">
  <div class="card-body">

      <div class="row">
        <div class="col-1">
        </div>
        <div class="col-10">
            <h3 style="text-align:center;">Your importing game is about to change forever.</h3>
            <h5 style="text-align:center;">Tired of the 0.01 ISK game?</h5>
            <h5 style="text-align:center;">Do you want to eat a bullet every time you have to edit your market spreadsheet?</h5>
            <h5 style="text-align:center;">Ever wonder how much ISK you're really making from importing?</h5>
            <h5 style="text-align:center;">Do you want your balance sheet to look like this?</h5>
            <span><img style="display:block;margin: 0 auto;" src="{% static 'img/route_performance.png' %}"></span><br>
            <div style="display:block; margin: 0 auto;text-align:center;">
                <img style="display:inline" src="{% static 'img/krabright.png' %}"><span style="display:inline;font-size:1.5rem;" > Start making billions with Krabacus </span><img  style="display:inline;"  src="{% static 'img/krableft.png' %}">
            </div>

            <a id="log-in-from-index-top" href="{% url 'sso:esi-login' %}"><img  style="display:block;margin: 0 auto;" src="{% static 'eve_sso_red.png' %}"></a>
            <br>
            <Br>
            <span  style="display:block; margin: 0 auto;text-align:center;">
                <a id="view-demo" href="{% url 'market:route-demo-view' %}"><h1><B>I'm not convinced, show me the demo</B></h1></a></span>
            </span>
            <h4 style="text-align:center;">~~Features~~</h4>
            <span  style="display:block; margin: 0 auto;text-align:center;">
                <h5>Automatic profit tracking</h5>
                <h5>0.01 ISK helper tool</h5>
                <h5>Scope out new markets with Eye of the Krab</h5>
                <h5>Shopping list with multibuy support</h5>
                <h5>Get notified when you sell out of an item</h5>
                <h5>Calculate accurate profit margins (including frieght and listing taxes!)</h5>
                <h5>Shows you breakeven price so you never accidentially sell at a loss</h5>
                <h5>Create multiple trade routes for different trade hubs</h5>
                <h5>View all of your market orders at a glance with tons of statistics</h5>
                <h5>View how profitable your past sales have been.</h5>
                <h5><span style="text-decoration:line-through;">Assets integration so you don't overimport stuff</span> (in progress cut me some slack)</h5>
                <br>
                <a id="log-in-from-index-bot" href="{% url 'sso:esi-login' %}"><img  style="display:block;margin: 0 auto;" src="{% static 'eve_sso_red.png' %}"></a>
            <br>
            </span>
        </div>
          <div class="col-1">
        </div>
      </div>
  </div>
</div>

{% endif %}

{% endblock %}

{% block footer %}
{% endblock %}