app/market/urls.py
from django.conf.urls import url

from .models import *
from .tasks import *
from .views import *
from .autocomplete import ItemGroupAutocomplete


app_name = 'market'
urlpatterns = [
    url(r'^item_group_autocomplete/$', ItemGroupAutocomplete.as_view(), name='item-group-autocomplete'),
    url(r'^routes/create/$', CreateRouteView.as_view(), name='create-route'),
    url(r'^routes/eye/data/(?P<pk>[0-9a-f-]+)/$', EyeofKrabData.as_view(), name='eye-data'),
    #url(r'^routes/eye/(?P<pk>\d+)/$', EyeOfKrabView.as_view(), name='eye-view'),
    url(r'^routes/view/(?P<pk>[0-9a-f-]+)/$', SingleRouteView.as_view(), name='route-view'),
    url(r'^routes/edit/$', EditRouteView.as_view(), name='route-edit'),
    url(r'^routes/delete/(?P<pk>[0-9a-f-]+)/$', DeleteRouteView.as_view(), name='route-delete'),
    #url(r'^routes/transactions/(?P<pk>\d+)/$', TransactionsView.as_view(), name='transaction-view'),
    url(r'^routes/transactions/data/(?P<pk>[0-9a-f-]+)/$', TransactionsData.as_view(), name='transaction-data'),
    url(r'^routes/orders/data/(?P<pk>[0-9a-f-]+)/$', OrdersData.as_view(), name='order-data'),
    url(r'^routes/orders/profit/(?P<pk>[0-9a-f-]+)/$', ProfitData.as_view(), name='profit-data'),
    url(r'^routes/shopping/edit/(?P<pk>[0-9a-f-]+)/$', shopping_list_edit_view, name='edit-shopping-list'),
    url(r'^routes/shopping/clear/(?P<pk>[0-9a-f-]+)/$', shopping_list_clear_view, name='clear-shopping-list'),
    url(r'^routes/shopping/data/(?P<pk>[0-9a-f-]+)/$', ShoppingListData.as_view(), name='shopping-list-data'),

    url(r'^routes/view/demo/$', SingleRouteDemoView.as_view(), name='route-demo-view'),

    url(r'^routes/$', RoutesView.as_view(), name='routes'),
]

app/sso/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from sso import views, auth_views
from sso.autocomplete import UserAutcomplete
from market.views import CreateRouteView

app_name = 'sso'
urlpatterns = [
    url(r'^$', views.ProfileView.as_view(), name='home'),

    # overwrites django default
    url(r'^login/$', auth_views.EsiLoginAsAuthenticationView.as_view(), name="esi-login"),
    url(r'^add_key/$', auth_views.EsiLoginToAddKeyView.as_view(), name="esi-add-key"),


    url(r'^o2/callback/$', auth_views.EsiLoginCallbackView.as_view(), name="esi-login-callback"),
    url(r'^user_autocomplete/$', UserAutcomplete.as_view(), name="user-autocomplete"),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profilefst/$', CreateRouteView.as_view(), name='profilefirst'),
    url(r'^analytics/$', views.AnalyticsView.as_view(), name='analytics'),
    url(r'^account/$', views.AccountView.as_view(), name='account'),
    url(r'^subscribe/$', views.AccountView.as_view(), name='subscribe'),
    url(r'^key_add_success/$', auth_views.KeyAddSuccessView.as_view(), name='key-add-success'),
    #url(r'roles', views.sso_role_view, name="sso-get-roles"),

]

app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib.auth import views as auth_views
#import registration.backends.default.views
from django.contrib.auth import views as auth_views

from utils import installed
#from sso.forms import RegistrationFormUniqueEmailBlocked
#from sso.custom_authorization_view import SpecialAuthorizationView

#from oauth2_provider import views as oauth_views

admin.autodiscover()
from django.conf import settings
from django.conf.urls import include, url
import logging


urlpatterns = [
    #url(r'^register/$', registration.backends.default.views.RegistrationView.as_view(form_class=RegistrationFormUniqueEmailBlocked)),

    url('', include('sso.urls')),
    url('', include('django.contrib.auth.urls')),
    url(r'^eve/', include('eve_api.urls')),
    url(r'^market/', include('market.urls')),
    url(r'^updates/', include('notifications.urls')),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #url(r'^o2/authorize/$', SpecialAuthorizationView.as_view(), name="authorize"),

    #url(r'^o2/token/$', oauth_views.TokenView.as_view(), name="token"),
    #url(r'^o2/revoke_token/$', oauth_views.RevokeTokenView.as_view(), name="revoke-token"),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if installed('sentry'):
    urlpatterns += [
        url(r'^sentry/', include('sentry.web.urls')),
    ]

if installed('nexus'):
    import nexus
    nexus.autodiscover()

    urlpatterns += [
        url(r'^admin/', include('nexus.site.urls')),
    ]
else:
    urlpatterns += [
        url(r'^admin/', admin.site.urls),
    ]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()


def handler500(request):
    """
    500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')
    return HttpResponseServerError(t.render({'request': request}))
    

app/market/models/item_group.py
import logging, uuid
from django.contrib.auth.models import User
from django.db import models
from eve_api.models import Structure, EVEPlayerCharacter, ObjectType
from .market_order import MarketOrder

logger=logging.getLogger(__name__)


class ItemGroup(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    creator = models.ForeignKey(User, default=None, null=True, on_delete=models.CASCADE)

    name = models.CharField(max_length=190)
    items = models.ManyToManyField(ObjectType)


    def __str__(self):
        return self.name

app/market/models/trading_route.py
import logging
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from eve_api.models import Structure, EVEPlayerCharacter, ObjectType
from .market_order import MarketOrder
from .item_group import ItemGroup
from .player_transaction import PlayerTransaction

logger=logging.getLogger(__name__)


class TradingRoute(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)
    colorblind = models.BooleanField(default=False)

    source_structure = models.ForeignKey(Structure, related_name="source_structure", on_delete=models.CASCADE)
    source_character = models.ForeignKey(EVEPlayerCharacter, related_name="source_character", on_delete=models.CASCADE)
    source_character_has_access = models.BooleanField(default=True)

    destination_structure = models.ForeignKey(Structure, related_name="destination_structure", on_delete=models.CASCADE)
    destination_character = models.ForeignKey(EVEPlayerCharacter, related_name="destination_character", on_delete=models.CASCADE)
    destination_character_has_access = models.BooleanField(default=True)

    cost_per_m3 = models.IntegerField()
    pct_collateral = models.FloatField()

    sales_tax = models.FloatField()
    broker_fee = models.FloatField(default=None,null=True)

    last_viewed = models.DateTimeField(default=None, null=True)

    item_groups = models.ManyToManyField(ItemGroup)

    @property
    def items(self):
        # todo: cache?
        return list(set(ObjectType.objects.filter(itemgroup__tradingroute=self)))

    @property
    def item_ids(self):
        # todo: cache?
        return list(set(ObjectType.objects.filter(itemgroup__tradingroute=self).values_list('ccp_id',flat=True)))

    def calculate_import_cost(self, object_type, quantity=1):
        # todo: remove?
        price = MarketOrder.get_minimum_sell_price(object_type, self.source_structure)
        if price is None:
            return None

        total_cost = price * float(quantity)
        collateral_cost = total_cost * self.pct_collateral

        volume_cost = self.calculate_freight(object_type, quantity)

        return collateral_cost + volume_cost

    def calculate_freight_m3(self, object_type, quantity=1):
        return object_type.packaged_volume * float(quantity) * float(self.cost_per_m3)

    def calculate_cogs_from_linkage(self, linkage):
        obj_type = linkage.source_transaction.object_type
        item_cost = linkage.source_transaction.unit_price * linkage.quantity_linked
        freight_cost_m3 = self.calculate_freight_m3(obj_type, linkage.quantity_linked)
        freight_cost_collat = item_cost * self.pct_collateral / 100
        fees = (self.broker_fee + self.sales_tax) / 100.0 * linkage.quantity_linked * linkage.destination_transaction.unit_price
        #print("tot cost: {}  freight m3 cost: {}  freight collat: {} fees: {}  units: {}".format(item_cost, freight_cost_m3, freight_cost_collat, fees, linkage.quantity_linked))
        return item_cost + freight_cost_collat + freight_cost_m3 + fees

    def estimate_cogs(self, object_type, quantity, unit_sell_price):
        possible_transactions = PlayerTransaction.objects.filter(
            character = self.source_character,
            location = self.source_structure,
            object_type = object_type,
            quantity_without_known_destination__gt=0
        ).order_by('unit_price')
        quantity_attributed = 0
        quantity_remaining = quantity
        value = 0.0
        for transaction in possible_transactions:
            if transaction.quantity_without_known_destination == quantity_remaining:
                q_attribed = quantity_remaining
            elif transaction.quantity_without_known_destination > quantity_remaining:
                q_attribed = quantity_remaining
            else:
                q_attribed = transaction.quantity_without_known_destination

            quantity_attributed += q_attribed
            quantity_remaining -= q_attribed
            value += q_attribed * transaction.unit_price
            if not quantity_remaining:
                break

        if quantity_remaining:
            # extrapolate for the rest
            if quantity_attributed:
                value = value * (quantity_attributed + quantity_remaining) / quantity_attributed
            else:
                # we have 0 quantity attributed.
                return None


        freight_cost_m3 = self.calculate_freight_m3(object_type, quantity)
        freight_cost_collat = value * self.pct_collateral / 100
        fees = (self.broker_fee + self.sales_tax) / 100.0 * quantity * unit_sell_price
        return value + freight_cost_collat + freight_cost_m3 + fees


    def __str__(self):
        return self.source_structure.location.system.name + " -> " + self.destination_structure.location.system.name

app/market/forms.py
from django import forms
from dal import autocomplete
from dal import forward
from django.forms.models import formset_factory
from django.forms import BaseFormSet
from django.http import QueryDict
from django.contrib.admin.widgets import FilteredSelectMultiple
from .models import *
from eve_api.models import Structure, EVEPlayerCharacter, ObjectType


class TradingRouteForm(forms.Form):
    source_character = forms.ModelChoiceField(
        EVEPlayerCharacter.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='eve_api:eveapi-character-autocomplete'
        )
    )

    source_structure = forms.ModelChoiceField(
        Structure.objects.all(),
        widget=autocomplete.ModelSelect2(
                url='eve_api:eveapi-structure-autocomplete',
                forward=[forward.Field('source_character', 'character')],
                attrs={
                    'data-minimum-input-length': 3,
                    'data-autocomplete-minimum-characters': 3,
                    'data-placeholder': "Structure Name (may take up to 10secs)"
                }
            )
    )

    price_per_m3 = forms.IntegerField(min_value=0, initial=1500)

    collateral_pct = forms.FloatField(min_value=0, max_value=1000, initial=1.00)
    sales_tax = forms.FloatField(min_value=0, max_value=100, initial=2.00)
    broker_fee = forms.FloatField(min_value=0, max_value=100, initial=3.00)

    destination_character = forms.ModelChoiceField(
        EVEPlayerCharacter.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='eve_api:eveapi-character-autocomplete'
        )
    )

    destination_structure = forms.ModelChoiceField(
        Structure.objects.all(),
        widget=autocomplete.ModelSelect2(
                url='eve_api:eveapi-structure-autocomplete',
                forward=[forward.Field('destination_character', 'character')],
                attrs={
                    'data-minimum-input-length': 3,
                    'data-autocomplete-minimum-characters': 3,
                    'data-placeholder': "Structure Name (may take up to 10secs)"
                }
            )
    )

    #item_groups = forms.ModelMultipleChoiceField(
    #    queryset=ItemGroup.objects.filter(creator__isnull=True),
    #    required=True,
    #    label="Item groups to import",
    #    widget=autocomplete.ModelSelect2Multiple(
    #            url='market:item-group-autocomplete',
    #            #Eforward=[forward.Field('source_character', 'character')],
    #            attrs={
    #                'data-minimum-input-length': 0,
    #                'data-autocomplete-minimum-characters': 0,
    #                'data-placeholder': ""
    #            }
    #        )
    #)



    class Meta:
        fields = ('__all__')


class EditShoppingListForm(forms.Form):
    object_type = forms.ModelChoiceField(ObjectType.objects.all())
    quantity = forms.IntegerField()

class EditRouteForm(forms.Form):
    route = forms.ModelChoiceField( queryset=TradingRoute.objects.all(), widget = forms.HiddenInput())
    price_per_m3 = forms.IntegerField(min_value=0)

    collateral_pct = forms.FloatField(min_value=0, max_value=1000)
    sales_tax = forms.FloatField(min_value=0, max_value=100)
    broker_fee = forms.FloatField(min_value=0, max_value=100)
    colorblind = forms.BooleanField(required=False)

app/market/views/route_config.py
from django.views.generic import TemplateView, FormView, View
from django.http import JsonResponse, HttpResponseRedirect, HttpResponseForbidden
from django.core.exceptions import PermissionDenied
from django.core.cache import cache
from django.template.response import TemplateResponse
from django.views.generic.detail import SingleObjectMixin
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.utils import timezone
from datetime import timedelta
from market.forms import TradingRouteForm

from market.models import ItemGroup, StructureMarketScanLog, MarketHistoryScanLog, PlayerTransactionScanLog, PlayerOrderScanLog, TradingRoute
from market.tasks import update_player_orders, update_region_market_history, update_player_transactions, update_structure_orders
from eve_api.models import ObjectType
from market.forms import EditRouteForm

from braces.views import LoginRequiredMixin


class DeleteRouteView(LoginRequiredMixin,SingleObjectMixin, View):
    template_name = 'market/delete_route.html'
    model = TradingRoute

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.object.creator == self.request.user:
            return HttpResponseForbidden()
        return TemplateResponse(request, 'market/delete_route.html', {"route":self.object})

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if not obj.creator == self.request.user:
            return HttpResponseForbidden()
        route_name = str(obj)
        obj.delete()
        messages.info(request, "{} route deleted".format(route_name))
        return HttpResponseRedirect(reverse_lazy("market:routes"))


class EditRouteView(LoginRequiredMixin, FormView):
    template_name = 'market/create_route.html'
    form_class = EditRouteForm
    success_url = reverse_lazy("market:routes")

    @staticmethod
    def get_populated_form(route):
        return EditRouteForm(initial={
            'route': route,
            'price_per_m3':route.cost_per_m3,
            'collateral_pct':route.pct_collateral,
            'sales_tax': route.sales_tax,
            'broker_fee': route.broker_fee,
            'colorblind': route.colorblind,
        })

    def form_valid(self, form):
        if form.is_valid():
            price_per_m3 = form.cleaned_data["price_per_m3"]
            collateral_pct = form.cleaned_data["collateral_pct"]
            sales_tax = form.cleaned_data["sales_tax"]
            broker_fee = form.cleaned_data["broker_fee"]
            colorblind = form.cleaned_data["colorblind"]


            route = form.cleaned_data["route"]
            if route.creator != self.request.user:
                raise PermissionDenied()

            route.cost_per_m3 = price_per_m3
            route.pct_collateral = collateral_pct
            route.sales_tax = sales_tax
            route.broker_fee = broker_fee
            route.colorblind = colorblind

            route.save()
            messages.info(self.request, "Route details updated.")
            self.success_url = reverse(viewname='market:route-view', args=[str(route.pk)])

            return super(EditRouteView, self).form_valid(form)

app/market/templates/market/create_route.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}
{% load waffle_tags %}

{% block title %}Create New Trading Route{% endblock %}

{% block css %}
{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
<div class="card">
<div class="card-body">
<h3>Create Trading Route</h3>
A Trading Route defines where you buy stuff, where you sell stuff, and what characters you do your buying/selling with. <br>
By providing this information, Krabacus can calculate how much profit you're making, how profitable it is to import items, and provide guidance on 0.01 ISK'ing the rest of the market.<br>
</div>
</div>
  <br>

<div id="app">

<form action="{% url 'market:create-route' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.source.errors }}
    {{ form.source }}

    <div class="card">
      <div class="card-body">
        <h5>Buying Location Information (AKA Source Information)</h5>
        Enter the character you'll be <b>buying</b> stuff with & the structure you'll be buying stuff in. <br>
        You must enter your buying character before the structure autocomplete will work.<br>
        Note: You must always use your buying character to purchase items for profit tracking to work.
      <table>

      <tr>
        <th>{{ form.source_character.label_tag }}</th>
        <td>
          {{ form.source_character.errors }}
          {{ form.source_character }}

          <a href="{% url 'sso:esi-add-key' %}" target="_blank"><img src="{% static 'key_button.png' %}"></a>
        </td>
      </tr>

      <tr>
        <th>{{ form.source_structure.label_tag }}</th>
        <td>
          {{ form.source_structure.errors }}
          <select name="source_structure" data-minimum-input-length="3" data-autocomplete-minimum-characters="3" data-placeholder="autocomplete is slow, bear with me" required id="id_source_structure" data-autocomplete-light-language="en-US" data-autocomplete-light-url="/eve/structure_autocomplete/" data-autocomplete-light-function="select2">
            <option value="" selected>---------</option>
            <option value="60003760">Jita IV - Moon 4 - Caldari Navy Assembly Plant</option>
            <option value="60008494">Amarr VIII (Oris) - Emperor Family Academy</option>

          </select><div style="display:none" class="dal-forward-conf" id="dal-forward-conf-for-id_source_structure"><script type="text/dal-forward-conf">[{"type": "field", "src": "source_character", "dst": "character"}]</script></div>
          <button class="btn btn-secondary btn-sm" type=button onclick="set_source_to_jita();">Use Jita</button>
          <button class="btn btn-secondary btn-sm" type=button onclick="set_source_to_amarr();">Use Amarr</button>
        </td>
      </tr>
    </table>
      </div>
    </div>

  <hr>

      <div class="card">
      <div class="card-body">
        <h5>Selling Location Information (AKA Destination Information)</h5>
        Enter the character you'll be <b>selling</b> stuff with & the structure you plan to sell things in.<br>
        You must enter your seller character before the structure autocomplete will work.<br>
        Note: You must always sell things with your seller character in order for profit tracking to work. If you have multiple characters you sell things with, create multiple routes.
    <table>
      <tr>
        <th>{{ form.destination_character.label_tag }}</th>
        <td>
          {{ form.destination_character.errors }}
          {{ form.destination_character }}
          <a href="{% url 'sso:esi-add-key' %}" target="_blank"><img src="{% static 'key_button.png' %}"></a>
        </td>
      </tr>

      <tr>
        <th>{{ form.destination_structure.label_tag }}</th>
        <td>
          {{ form.destination_structure.errors }}
          <select name="destination_structure" data-minimum-input-length="3" data-autocomplete-minimum-characters="3" data-placeholder="autocomplete is slow, bear with me" required id="id_destination_structure" data-autocomplete-light-language="en-US" data-autocomplete-light-url="/eve/structure_autocomplete/" data-autocomplete-light-function="select2">
            <option value="" selected>---------</option>
            <option value="60003760">Jita IV - Moon 4 - Caldari Navy Assembly Plant</option>
            <option value="60008494">Amarr VIII (Oris) - Emperor Family Academy</option>

          </select><div style="display:none" class="dal-forward-conf" id="dal-forward-conf-for-id_destination_structure"><script type="text/dal-forward-conf">[{"type": "field", "src": "destination_character", "dst": "character"}]</script></div>

          <button class="btn btn-secondary btn-sm" type=button onclick="set_dest_to_jita();">Use Jita</button>
          <button class="btn btn-secondary btn-sm" type=button onclick="set_dest_to_amarr();">Use Amarr</button>
        </td>
        <td>

        </td>
      </tr>

  </table>
      </div></div>

  <hr>

    <div class="card">
      <div class="card-body">
        <h5>Other Route Information/Overhead</h5>
        In order to accurately calculate how profitable items are, Krabacus needs to know how much it costs to ship items and how much it costs for you to post items on the destination market.<br>
        If you don't know the destination structure's sales tax/broker fee, you can just leave the defaults until you can figure it out.
    <table>

      <tr>
        <th>Shipping Cost per m3</th>
        <td>
          {{ form.price_per_m3.errors }}
            <div class="input-group mb-3">
              <input  id="id_price_per_m3" value="{{form.price_per_m3.value}}" type="number" name="price_per_m3" step="any" required="" id="id_price_per_m3" class="form-control" placeholder="1000" >
              <div class="input-group-append">
                <span class="input-group-text">ISK/m3</span>
              </div>
            </div>
        </td>
      </tr>

      <tr>
        <th>Shipping Collateral Cost</th>
        <td>
          {{ form.collateral_pct.errors }}
            <div class="input-group mb-3">
              <input  type="number" value="{{form.collateral_pct.value}}" name="collateral_pct" step="any" required="" id="id_collateral_pct" class="form-control" placeholder="1.00" >
              <div class="input-group-append">
                <span class="input-group-text">% of Collateral</span>
              </div>
            </div>
        </td>
      </tr>


      <tr>
        <th>Destination Structure Sales Tax</th>
        <td>
          {{ form.sales_tax.errors }}
            <div class="input-group mb-3">
              <input  type="number" value="{{form.sales_tax.value}}" name="sales_tax" step="any" required="" id="id_sales_tax" class="form-control">
              <div class="input-group-append">
                <span class="input-group-text">%</span>
              </div>
            </div>
        </td>
      </tr>

      <tr>
        <th>Destination Structure Broker Fee</th>
        <td>
          {{ form.broker_fee.errors }}
            <div class="input-group mb-3">
              <input  type="number" value="{{form.broker_fee.value}}" name="broker_fee" step="any" required="" id="id_broker_fee" class="form-control">
              <div class="input-group-append">
                <span class="input-group-text">%</span>
              </div>
            </div>
        </td>
      </tr>
    </table>
      </div>
    </div>
  <br>
    <div class="card">
      <div class="card-body">
  <button type="submit" class="btn btn-lg btn-success btn-block">Create Trading Route</button>
      </div>
    </div>
</form>
    </div>
{% endblock %}


{% block footer %}
<script>
  //spent 2 hours trying to do this 'correctly', i'm over it now and will settle with the hack
  function set_source_to_jita(){
    $("select[name^='source_structure']").select().val('60003760');
    $("#select2-id_source_structure-container")[0].innerText = "Jita IV - Moon 4 - Caldari Navy Assembly Plant"
    $("select[name^='source_structure']").select().trigger('change'); /// im pretty sure this doesnt do anything
  };

  function set_source_to_amarr(){
    $("select[name^='source_structure']").select().val('60008494');
    $("#select2-id_source_structure-container")[0].innerText = "Amarr VIII (Oris) - Emperor Family Academy"
    $("select[name^='source_structure']").select().trigger('change'); /// im pretty sure this doesnt do anything
  };
  
  function set_dest_to_jita(){
    $("select[name^='destination_structure']").select().val('60003760');
    $("#select2-id_destination_structure-container")[0].innerText = "Jita IV - Moon 4 - Caldari Navy Assembly Plant"
    $("select[name^='destination_structure']").select().trigger('change'); /// im pretty sure this doesnt do anything
  };

  function set_dest_to_amarr(){
    $("select[name^='destination_structure']").select().val('60008494');
    $("#select2-id_destination_structure-container")[0].innerText = "Amarr VIII (Oris) - Emperor Family Academy"
    $("select[name^='destination_structure']").select().trigger('change'); /// im pretty sure this doesnt do anything
  };


function create_route_post(event) {
  gtag('event', 'click', {
    'event_label' : 'Create Route Button'
  });
  };


</script>
{{form.media}}
{% endblock %}

app/market/templates/market/delete_route.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}
{% load waffle_tags %}

{% block title %}Delete Trading Route Confirmation{% endblock %}

{% block css %}
{% endblock %}



{% block content %}
<h2>Are you sure you want to delete {{route}}?</h2>
<form action="{% url 'market:route-delete' route.pk %}" method="post">
    {% csrf_token %}
<button type="submit" class="btn btn-danger">Yes, delete this route</button>
</form>

{% endblock %}


{% block footer %}
{% endblock %}

app/market/templates/market/eye_of_the_krab_wrapper.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}
{% load waffle_tags %}

{% block title %}Trading Routes{% endblock %}

{% block css %}
{% endblock %}



{% block content %}

{% include 'market/eye_of_the_krab.html' %}

{% endblock %}




{% block footer %}
{% endblock %}

app/market/templates/market/profit_tracker.html
{% load fmt_isk %}
{% load fmt_int %}
{% load fmt_float %}

<span style="font-size:14px;" class="badge badge-secondary">
Route performance over the past 30 days. Total Profit: <span id="profit-amount">N/A</span>
</span>

<table class="table table-striped table-bordered" id="table-profit-tracker">
<thead>
<tr>

</tr>
    {% for field in profit_fields %}
        <th >{{field}}</th>
    {% endfor %}
</thead>
    <tbody>
    </tbody>

</table>

<script>
var name_column = 0;
//var qty_purchased_col = 1;
var qty_sold_col = 1;
//var qty_on_market_col = 3;
var avg_sell_rate_col = 2;
var avg_profit_col = 3;
var total_profit_col = 4;


$(function () {
  $('#table-profit-tracker').DataTable({
    searching: false,
    pageLength: 500,
    processing: true,
    serverSide: true,
    deferLoading: 0,
    order: [[ total_profit_col, "desc" ]],
    lengthChange: false,
    select: true,
    ajax: "{% url 'market:profit-data' route.pk %}",
    language: {
        'processing':'Retrieving table data.',
        'loadingRecords': '&nbsp;',
        },
    columnDefs: [
            {
                "render": function ( data, type, row ) {return fmt_quantity_small(data) + " units/day";},
                "targets": avg_sell_rate_col
            },
            {
                "render": function ( data, type, row ) {return fmt_quantity(data);},
                "targets": qty_sold_col
            },
            {
                "render": function ( data, type, row ) {return fmt_isk(data);},
                "targets": avg_profit_col
            },
            {
                "render": function ( data, type, row ) {return fmt_isk(data);},
                "targets": total_profit_col
            },
            { "visible": false,  "targets": [] }
        ],
    drawCallback: function () {
          var api = this.api();
          var sum = 0;
          var d = api.column( 4, {page:'current'} ).data();
          for(var s=0; s<d.length; s++){
            sum += d[s];
          }
          $("#profit-amount").text(fmt_isk(sum) + " ISK");

        }
  });
  });



function profit_loader(event){
    $('#table-profit-tracker').DataTable().draw();
    //$('#table-profit-tracker').DataTable().select.items('row');
};
</script>